version: "3.9"

services:
  roundcube:
    image: roundcube/roundcubemail:custom
    volumes:
      - /root/config/:/var/roundcube/config/
    ports:
      - 80:80
    environment:
      - ROUNDCUBEMAIL_DEFAULT_HOST=ssl://mail.aibdt.com.tw
      - ROUNDCUBEMAIL_SMTP_SERVER=ssl://mail.aibdt.com.tw
      - ROUNDCUBEMAIL_SKIN=elastic
      - ROUNDCUBEMAIL_PLUGINS=archive,zipdownload,contextmenu,newmail_notifier,help,attachment_reminder
      - ROUNDCUBEMAIL_DB_TYPE=pgsql
      - ROUNDCUBEMAIL_DB_HOST=pgsql
      - ROUNDCUBEMAIL_DB_USER=roundcube
      - ROUNDCUBEMAIL_DB_PASSWORD=roundcube
      - ROUNDCUBEMAIL_DB_NAME=roundcube
    depends_on:
      - pgsql

  pgsql:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=roundcube
      - POSTGRES_USER=roundcube
      - POSTGRES_PASSWORD=roundcube
    volumes:
      # add volume so data will not disappear
      - /root/pgsql/:/var/lib/postgresql/data/
